// angular-native/src/app/screens/starred-screen.ts
import { Component, inject, output } from '@angular/core';
import { NotesStore } from '../data/notes-store.ts';
import { NoteList } from '../ui/note-list.ts';
import { ScreenHeader } from '../ui/screen-header.ts';

@Component({
  selector: 'app-starred-screen',
  imports: [NoteList, ScreenHeader],
  host: { style: 'flex: 1' },
  template: `
    <app-screen-header title="Starred" />
    <app-note-list
      [notes]="store.starred()"
      [showSnippets]="store.showSnippets()"
      [ready]="store.loaded()"
      emptyText="No starred notes"
      (open)="open.emit($event)"
    />
  `,
})
export class StarredScreen {
  protected readonly store = inject(NotesStore);
  readonly open = output<string>();
}

// lynx/src/screens/StarredScreen.tsx
import { NoteList } from '../components/NoteList.js';
import { ScreenHeader } from '../components/ScreenHeader.js';
import type { Note } from '../data/types.js';

export function StarredScreen({ notes, showSnippets, onOpen }: {
  notes: Note[];
  showSnippets: boolean;
  onOpen: (id: string) => void;
}) {
  return (
    <view style={{ flexGrow: 1, flexShrink: 1, flexBasis: '0px', display: 'flex', flexDirection: 'column' }}>
      <ScreenHeader title='Starred' />
      <NoteList
        notes={notes.filter((n) => n.starred)}
        showSnippets={showSnippets}
        emptyText='No starred notes'
        onOpen={onOpen}
      />
    </view>
  );
}
