// lynx/src/components/NoteCard.tsx
import { dateLabel, noteSnippet, noteTitle } from '../data/notes.js';
import { noteTags } from '../data/tags.js';
import { taskProgress } from '../data/tasks.js';
import type { Note } from '../data/types.js';
import { a11y, colors } from '../theme.js';

export function NoteCard({ note, showSnippet, first, onOpen }: {
  note: Note;
  showSnippet: boolean;
  first: boolean;
  onOpen: (id: string) => void;
}) {
  const title = noteTitle(note.body);
  const snippet = showSnippet ? noteSnippet(note.body) : '';
  const tags = noteTags(note.body);
  const progress = taskProgress(note.body);
  return (
    <view
      {...a11y('note-card', title, { 'accessibility-traits': 'button' })}
      style={{
        marginTop: first ? '0px' : '12px',
        marginLeft: '16px',
        marginRight: '16px',
        padding: '16px',
        borderRadius: '14px',
        backgroundColor: colors.surface,
        display: 'flex',
        flexDirection: 'column',
      }}
      bindtap={() => onOpen(note.id)}
    >
      <text
        text-maxline='1'
        style={{ fontSize: '17px', lineHeight: '22px', fontWeight: '600', color: colors.text, textOverflow: 'ellipsis', overflow: 'hidden' }}
      >
        {title}
      </text>
      {snippet !== '' ? (
        <text
          text-maxline='2'
          style={{
            marginTop: '4px',
            fontSize: '15px',
            lineHeight: '20px',
            color: colors.textSecondary,
            textOverflow: 'ellipsis',
            overflow: 'hidden',
          }}
        >
          {snippet}
        </text>
      ) : null}
      {tags.length > 0 ? (
        <view style={{ marginTop: '8px', height: '22px', display: 'flex', flexDirection: 'row', overflow: 'hidden' }}>
          {tags.map((t, i) => (
            <view
              key={t}
              style={{
                flexShrink: 0,
                height: '22px',
                marginLeft: i === 0 ? '0px' : '6px',
                paddingLeft: '8px',
                paddingRight: '8px',
                borderRadius: '11px',
                backgroundColor: colors.accentSoft,
                display: 'flex',
                alignItems: 'center',
              }}
            >
              <text style={{ fontSize: '12px', fontWeight: '500', color: colors.accent }}>{`#${t}`}</text>
            </view>
          ))}
        </view>
      ) : null}
      <view
        style={{ marginTop: '8px', display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}
      >
        <view style={{ display: 'flex', flexDirection: 'row', alignItems: 'center' }}>
          <text style={{ fontSize: '13px', lineHeight: '18px', color: colors.textTertiary }}>{dateLabel(note.updatedAt)}</text>
          {progress ? (
            <text style={{ marginLeft: '12px', fontSize: '13px', lineHeight: '18px', color: colors.textSecondary }}>
              {`${progress.done}/${progress.total} done`}
            </text>
          ) : null}
        </view>
        {note.starred ? <text style={{ fontSize: '16px', lineHeight: '18px', color: colors.star }}>{'★'}</text> : null}
      </view>
    </view>
  );
}

// angular-native/src/app/ui/note-card.ts
import { Component, computed, input, output } from '@angular/core';
import { Pressable, Text, View } from '@ng-native/components';
import { type Note, formatDate, noteSnippet, noteTags, noteTitle, taskProgress } from '../data/note.ts';

@Component({
  selector: 'app-note-card',
  imports: [Pressable, Text, View],
  template: `
    <pressable
      testID="note-card"
      accessibilityRole="button"
      class="card"
      #p="pressable"
      [style.opacity]="p.pressed() ? 0.7 : 1"
      (press)="open.emit(note().id)"
    >
      <text class="title" [numberOfLines]="1">{{ title() }}</text>
      @if (showSnippet() && snippet()) {
        <text class="snippet" [numberOfLines]="2">{{ snippet() }}</text>
      }
      @if (tags().length > 0) {
        <view class="chips">
          @for (tag of tags(); track tag) {
            <view class="chip">
              <text class="chip-text" [numberOfLines]="1">#{{ tag }}</text>
            </view>
          }
        </view>
      }
      <view class="footer">
        <view class="meta">
          <text class="date">{{ date() }}</text>
          @if (progress().total > 0) {
            <text class="progress">{{ progress().done }}/{{ progress().total }} done</text>
          }
        </view>
        @if (note().starred) {
          <text class="star">★</text>
        }
      </view>
    </pressable>
  `,
  styles: `
    .card {
      background-color: var(--surface);
      border-radius: 14px;
      padding: 16px;
    }
    .title {
      font-size: 17px;
      line-height: 22px;
      font-weight: 600;
      color: var(--text);
    }
    .snippet {
      margin-top: 4px;
      font-size: 15px;
      line-height: 20px;
      color: var(--text-secondary);
    }
    .chips {
      margin-top: 8px;
      flex-direction: row;
      gap: 6px;
      overflow: hidden;
    }
    .chip {
      height: 22px;
      padding-left: 8px;
      padding-right: 8px;
      border-radius: 11px;
      background-color: var(--accent-soft);
      justify-content: center;
      flex-shrink: 0;
    }
    .chip-text {
      font-size: 12px;
      font-weight: 500;
      color: var(--accent);
    }
    .footer {
      margin-top: 8px;
      flex-direction: row;
      align-items: center;
      justify-content: space-between;
      height: 18px;
    }
    .date {
      font-size: 13px;
      line-height: 18px;
      color: var(--text-tertiary);
    }
    .meta {
      flex-direction: row;
      align-items: center;
      gap: 12px;
    }
    .progress {
      font-size: 13px;
      line-height: 18px;
      color: var(--text-secondary);
    }
    .star {
      font-size: 16px;
      line-height: 18px;
      color: var(--star);
    }
  `,
})
export class NoteCard {
  readonly note = input.required<Note>();
  readonly showSnippet = input(true);
  readonly open = output<string>();

  protected readonly title = computed(() => noteTitle(this.note().body));
  protected readonly snippet = computed(() => noteSnippet(this.note().body));
  protected readonly tags = computed(() => noteTags(this.note().body));
  protected readonly progress = computed(() => taskProgress(this.note().body));
  protected readonly date = computed(() => formatDate(this.note().updatedAt));
}
