// react-native/src/ui/Toast.tsx
import React from 'react';
import { Pressable, Text, View } from 'react-native';
import { makeStyles } from '../theme';

export function Toast({ message, bottom, onUndo }: { message: string; bottom: number; onUndo: () => void }) {
  const styles = useStyles();
  return (
    <View testID="toast" style={[styles.toast, { bottom }]}>
      <Text style={styles.message}>{message}</Text>
      <Pressable testID="undo-button" accessibilityRole="button" accessibilityLabel="Undo" onPress={onUndo} hitSlop={10}>
        <Text style={styles.undo}>Undo</Text>
      </Pressable>
    </View>
  );
}

const useStyles = makeStyles((colors) => ({
  toast: {
    position: 'absolute',
    left: 16,
    right: 16,
    height: 48,
    borderRadius: 12,
    backgroundColor: colors.toastBg,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  message: { fontSize: 15, color: '#FFFFFF' },
  undo: { fontSize: 15, fontWeight: '600', color: '#A79FFF' },
}));

// angular-native/src/app/ui/toast.ts
import { Component, output } from '@angular/core';
import { Pressable, Text, View } from '@ng-native/components';

/** Dark "Note deleted · Undo" snackbar. Positioning is left to the parent. */
@Component({
  selector: 'app-toast',
  imports: [Pressable, Text, View],
  template: `
    <view testID="toast" class="toast">
      <text class="message">Note deleted</text>
      <pressable testID="undo-button" accessibilityRole="button" class="undo" [hitSlop]="10" (press)="undo.emit()">
        <text class="undo-text">Undo</text>
      </pressable>
    </view>
  `,
  styles: `
    .toast {
      height: 48px;
      border-radius: 12px;
      background-color: var(--toast-bg);
      padding-left: 16px;
      padding-right: 16px;
      flex-direction: row;
      align-items: center;
      justify-content: space-between;
    }
    .message {
      font-size: 15px;
      color: #ffffff;
    }
    .undo {
      height: 48px;
      justify-content: center;
    }
    .undo-text {
      font-size: 15px;
      font-weight: 600;
      color: #a79fff;
    }
  `,
})
export class Toast {
  readonly undo = output<void>();
}
