// angular-native/src/app/screens/editor-screen.ts
import { Component, computed, inject, input, output, signal } from '@angular/core';
import { Pressable, ScrollView, Text, TextInput, View } from '@ng-native/components';
import { Keyboard, SafeArea, Sharing } from '@ng-native/device';
import { toggleTask } from '../data/note.ts';
import { NotesStore } from '../data/notes-store.ts';
import { KEYBOARD_EXCLUDES_BOTTOM_INSET } from '../platform.ts';
import { MarkdownView } from '../markdown/markdown-view.ts';
import { type EditorMode, SegmentedControl } from '../ui/segmented-control.ts';

@Component({
  selector: 'app-editor-screen',
  imports: [MarkdownView, Pressable, ScrollView, SegmentedControl, Text, TextInput, View],
  host: { style: 'flex: 1' },
  template: `
    <view class="nav">
      <pressable
        testID="back-button"
        accessibilityRole="button"
        class="back"
        [hitSlop]="8"
        #b="pressable"
        [style.opacity]="b.pressed() ? 0.5 : 1"
        (press)="back.emit()"
      >
        <text class="back-text">‹ Notes</text>
      </pressable>
      <view class="actions">
      <pressable
        testID="share-button"
        accessibilityRole="button"
        class="delete"
        [hitSlop]="8"
        #sh="pressable"
        [style.opacity]="sh.pressed() ? 0.5 : 1"
        (press)="share()"
      >
        <text class="share-text">Share</text>
      </pressable>
      <pressable
        testID="delete-button"
        accessibilityRole="button"
        class="delete"
        [hitSlop]="8"
        #d="pressable"
        [style.opacity]="d.pressed() ? 0.5 : 1"
        (press)="delete.emit()"
      >
        <text class="delete-text">Delete</text>
      </pressable>
      <pressable
        testID="star-button"
        accessibilityRole="button"
        [accessibilityLabel]="starred() ? 'Unstar' : 'Star'"
        [accessibilityState]="{ selected: starred() }"
        class="star"
        (press)="toggleStar()"
      >
        <text class="star-text" [class.starred]="starred()">{{ starred() ? '★' : '☆' }}</text>
      </pressable>
      </view>
    </view>

    <view class="segments">
      <app-segmented-control [mode]="mode()" (change)="setMode($event)" />
    </view>

    @if (mode() === 'edit') {
      <view class="card" [style.marginBottom]="cardBottom()">
        <text-input
          testID="editor-input"
          class="input"
          [multiline]="true"
          [autoFocus]="focusOnMount()"
          autoCapitalize="sentences"
          [autoCorrect]="false"
          [smartInsertDelete]="false"
          [value]="body()"
          (changeText)="onChange($event)"
        />
      </view>
    } @else {
      <scroll-view
        testID="preview-view"
        class="preview"
        [contentContainerStyle]="{ paddingTop: 12, paddingHorizontal: 20, paddingBottom: safeArea.insets().bottom + 16 }"
      >
        <app-markdown-view [source]="body()" (toggleTask)="onToggleTask($event)" />
      </scroll-view>
    }
  `,
  styles: `
    .nav {
      height: 44px;
      flex-direction: row;
      align-items: center;
      justify-content: space-between;
      background-color: var(--bg);
    }
    .back {
      padding-left: 16px;
      height: 44px;
      justify-content: center;
    }
    .back-text {
      font-size: 17px;
      color: var(--accent);
    }
    .actions {
      flex-direction: row;
      align-items: center;
      gap: 12px;
    }
    .delete {
      height: 44px;
      justify-content: center;
    }
    .share-text {
      font-size: 17px;
      color: var(--accent);
    }
    .delete-text {
      font-size: 17px;
      color: var(--danger);
    }
    .star {
      width: 44px;
      height: 44px;
      margin-right: 16px;
      align-items: center;
      justify-content: center;
    }
    .star-text {
      font-size: 22px;
      color: var(--text-tertiary);
    }
    .starred {
      color: var(--star);
    }
    .segments {
      margin-top: 4px;
      margin-left: 16px;
      margin-right: 16px;
    }
    .card {
      flex: 1;
      margin-top: 12px;
      margin-left: 16px;
      margin-right: 16px;
      padding: 16px;
      border-radius: 14px;
      background-color: var(--surface);
    }
    .input {
      flex: 1;
      padding: 0;
      font-family: var(--mono, Menlo);
      font-size: 15px;
      line-height: 22px;
      color: var(--text);
    }
    .preview {
      flex: 1;
    }
  `,
})
export class EditorScreen {
  private readonly store = inject(NotesStore);
  private readonly keyboard = inject(Keyboard);
  protected readonly safeArea = inject(SafeArea);
  private readonly sharing = inject(Sharing);
  private readonly keyboardExcludesInset = inject(KEYBOARD_EXCLUDES_BOTTOM_INSET);

  readonly noteId = input.required<string>();
  readonly isNew = input(false);
  readonly back = output<void>();
  readonly delete = output<void>();

  private readonly chosenMode = signal<EditorMode | null>(null);
  protected readonly mode = computed<EditorMode>(() => this.chosenMode() ?? (this.isNew() ? 'edit' : 'preview'));
  /** Only a freshly created note raises the keyboard on its own. */
  protected readonly focusOnMount = computed(() => this.isNew() && this.chosenMode() === null);

  private readonly note = computed(() => this.store.get(this.noteId()));
  protected readonly body = computed(() => this.note()?.body ?? '');
  protected readonly starred = computed(() => this.note()?.starred ?? false);

  protected readonly cardBottom = computed(() => {
    const kb = this.keyboard.height();
    const inset = this.safeArea.insets().bottom;
    if (kb <= 0) return inset + 16;
    return kb + (this.keyboardExcludesInset ? inset : 0) + 16;
  });

  protected setMode(mode: EditorMode): void {
    if (mode === 'preview') this.keyboard.dismiss();
    this.chosenMode.set(mode);
  }

  protected onChange(text: string): void {
    this.store.updateBody(this.noteId(), text);
  }

  protected onToggleTask(index: number): void {
    const next = toggleTask(this.body(), index);
    if (next !== this.body()) this.store.updateBody(this.noteId(), next);
  }

  /** Opens the native share sheet (UIActivityViewController / Android chooser) with the raw markdown. */
  protected share(): void {
    this.keyboard.dismiss();
    void this.sharing.share({ message: this.body() }).catch((error: unknown) => {
      console.warn('[editor] share failed', error);
    });
  }

  protected toggleStar(): void {
    this.store.toggleStar(this.noteId());
  }
}

// react-native/src/screens/EditorScreen.tsx
import React, { useEffect, useRef, useState } from 'react';
import { BackHandler, Keyboard, Platform, Pressable, Share, ScrollView, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useNotes } from '../data/NotesStore';
import type { Note } from '../data/types';
import { makeStyles, useColors, useTheme, mono } from '../theme';
import { MarkdownView } from '../markdown/MarkdownView';
import { Segmented } from '../ui/Segmented';
import { toggleTask } from '../data/tasks';

type Mode = 'edit' | 'preview';

export function EditorScreen({
  noteId,
  isNew,
  onClose,
  onDeleted,
}: {
  noteId: string;
  isNew: boolean;
  onClose: () => void;
  onDeleted: (note: Note) => void;
}) {
  const styles = useStyles();
  const colors = useColors();
  const { dark } = useTheme();
  const { getNote, updateBody, toggleStar, deleteNote } = useNotes();
  const note = getNote(noteId);
  const insets = useSafeAreaInsets();
  const [mode, setMode] = useState<Mode>(isNew ? 'edit' : 'preview');
  const [body, setBody] = useState(note?.body ?? '');
  const [keyboardHeight, setKeyboardHeight] = useState(0);
  const bodyRef = useRef(body);

  useEffect(() => {
    // Android has no keyboardWill* events; its Did* events fire once the IME has settled.
    const ios = Platform.OS === 'ios';
    const show = Keyboard.addListener(ios ? 'keyboardWillShow' : 'keyboardDidShow', (e) =>
      setKeyboardHeight(e.endCoordinates.height),
    );
    const hide = Keyboard.addListener(ios ? 'keyboardWillHide' : 'keyboardDidHide', () => setKeyboardHeight(0));
    return () => {
      show.remove();
      hide.remove();
    };
  }, []);

  const onChangeText = (text: string) => {
    bodyRef.current = text;
    setBody(text);
    updateBody(noteId, text); // persisted synchronously to SQLite
  };

  const goBack = () => {
    Keyboard.dismiss();
    if (bodyRef.current.trim().length === 0) deleteNote(noteId);
    onClose();
  };

  // Android system back (button/gesture) behaves like the `‹ Notes` button instead of leaving the app.
  const goBackRef = useRef(goBack);
  goBackRef.current = goBack;
  useEffect(() => {
    const sub = BackHandler.addEventListener('hardwareBackPress', () => {
      goBackRef.current();
      return true;
    });
    return () => sub.remove();
  }, []);

  // Native share sheet (UIActivityViewController) with the raw markdown as plain text.
  const onShare = () => {
    Keyboard.dismiss();
    Share.share({ message: bodyRef.current }).catch(() => {});
  };

  const onDelete = () => {
    Keyboard.dismiss();
    const snapshot = getNote(noteId);
    deleteNote(noteId);
    onClose();
    if (snapshot) onDeleted(snapshot);
  };

  const starred = note?.starred ?? false;
  // On Android the reported keyboard height excludes the navigation bar inset (edge-to-edge window).
  const keyboardSpace = Platform.OS === 'android' ? keyboardHeight + insets.bottom : keyboardHeight;
  const bottomSpace = (keyboardHeight > 0 ? keyboardSpace : insets.bottom) + 16;

  return (
    <View style={styles.flex}>
      <View style={styles.nav}>
        <Pressable
          testID="back-button"
          accessibilityRole="button"
          accessibilityLabel="Notes"
          onPress={goBack}
          style={styles.back}
          hitSlop={8}
        >
          <Text style={styles.backText}>‹ Notes</Text>
        </Pressable>
        <View style={styles.navRight}>
        <Pressable
          testID="share-button"
          accessibilityRole="button"
          accessibilityLabel="Share"
          onPress={onShare}
          style={styles.shareHit}
          hitSlop={8}
        >
          <Text style={styles.shareText}>Share</Text>
        </Pressable>
        <Pressable
          testID="delete-button"
          accessibilityRole="button"
          accessibilityLabel="Delete"
          onPress={onDelete}
          style={styles.deleteHit}
          hitSlop={8}
        >
          <Text style={styles.deleteText}>Delete</Text>
        </Pressable>
        <Pressable
          testID="star-button"
          accessibilityRole="button"
          accessibilityLabel={starred ? 'Unstar' : 'Star'}
          accessibilityState={{ selected: starred }}
          onPress={() => toggleStar(noteId)}
          style={styles.starHit}
        >
          <Text style={[styles.star, { color: starred ? colors.star : colors.textTertiary }]}>{starred ? '★' : '☆'}</Text>
        </Pressable>
        </View>
      </View>
      <View style={styles.segmentWrap}>
        <Segmented<Mode>
          segments={[
            { key: 'edit', label: 'Edit', testID: 'mode-edit' },
            { key: 'preview', label: 'Preview', testID: 'mode-preview' },
          ]}
          value={mode}
          onChange={(m) => {
            if (m === 'preview') Keyboard.dismiss();
            setMode(m);
          }}
        />
      </View>
      {mode === 'edit' ? (
        <View style={[styles.editCard, { marginBottom: bottomSpace }]}>
          <TextInput
            testID="editor-input"
            accessibilityLabel="Note text"
            style={styles.input}
            value={body}
            onChangeText={onChangeText}
            multiline
            autoFocus={isNew}
            scrollEnabled
            textAlignVertical="top"
            autoCorrect={false}
            autoCapitalize="sentences"
            smartInsertDelete={false}
            keyboardAppearance={dark ? 'dark' : 'light'}
            selectionColor={colors.accent}
          />
        </View>
      ) : (
        <ScrollView
          testID="preview-view"
          style={styles.flex}
          contentContainerStyle={[styles.preview, { paddingBottom: insets.bottom + 16 }]}
        >
          <MarkdownView source={body} onToggleTask={(i) => onChangeText(toggleTask(bodyRef.current, i))} />
        </ScrollView>
      )}
    </View>
  );
}

const useStyles = makeStyles((colors) => ({
  flex: { flex: 1 },
  nav: { height: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: colors.bg },
  back: { paddingLeft: 16, height: 44, justifyContent: 'center' },
  backText: { fontSize: 17, color: colors.accent },
  navRight: { flexDirection: 'row', alignItems: 'center' },
  shareHit: { height: 44, justifyContent: 'center', marginRight: 12 },
  shareText: { fontSize: 17, color: colors.accent },
  deleteHit: { height: 44, justifyContent: 'center', marginRight: 12 },
  deleteText: { fontSize: 17, color: colors.danger },
  starHit: { width: 44, height: 44, marginRight: 16, alignItems: 'center', justifyContent: 'center' },
  star: { fontSize: 22 },
  segmentWrap: { marginTop: 4 },
  editCard: { flex: 1, marginTop: 12, marginHorizontal: 16, backgroundColor: colors.surface, borderRadius: 14, padding: 16 },
  input: { flex: 1, padding: 0, fontFamily: mono, fontSize: 15, lineHeight: 22, color: colors.text },
  preview: { paddingHorizontal: 20, paddingTop: 12 },
}));
