// angular-native/src/app/screens/starred-screen.ts
import { Component, inject, output } from '@angular/core';
import { NotesStore } from '../data/notes-store.ts';
import { NoteList } from '../ui/note-list.ts';
import { ScreenHeader } from '../ui/screen-header.ts';

@Component({
  selector: 'app-starred-screen',
  imports: [NoteList, ScreenHeader],
  host: { style: 'flex: 1' },
  template: `
    <app-screen-header title="Starred" />
    <app-note-list
      [notes]="store.starred()"
      [showSnippets]="store.showSnippets()"
      [ready]="store.loaded()"
      emptyText="No starred notes"
      (open)="open.emit($event)"
    />
  `,
})
export class StarredScreen {
  protected readonly store = inject(NotesStore);
  readonly open = output<string>();
}

// react-native/src/screens/StarredScreen.tsx
import React, { useMemo } from 'react';
import { View } from 'react-native';
import { useNotes } from '../data/NotesStore';
import { sortNotes } from '../data/noteText';
import { NoteList } from '../ui/NoteList';
import { ScreenHeader } from '../ui/ScreenHeader';

export function StarredScreen({ onOpen }: { onOpen: (id: string) => void }) {
  const { notes, settings } = useNotes();
  const starred = useMemo(
    () => sortNotes(notes.filter((n) => n.starred), settings.sortBy),
    [notes, settings.sortBy],
  );
  return (
    <View style={{ flex: 1 }}>
      <ScreenHeader title="Starred" />
      <NoteList notes={starred} showSnippets={settings.showSnippets} emptyText="No starred notes" onOpen={onOpen} />
    </View>
  );
}
