// lynx/src/screens/SettingsScreen.tsx
import { ScreenHeader } from '../components/ScreenHeader.js';
import { Switch } from '../components/Switch.js';
import type { Appearance, Settings } from '../data/types.js';

const APPEARANCE_LABEL: Record<Appearance, string> = { system: 'System', light: 'Light', dark: 'Dark' };
const NEXT_APPEARANCE: Record<Appearance, Appearance> = { system: 'light', light: 'dark', dark: 'system' };
import { a11y, colors } from '../theme.js';

const groupStyle = () => ({
  marginLeft: '16px',
  marginRight: '16px',
  borderRadius: '14px',
  backgroundColor: colors.surface,
  display: 'flex',
  flexDirection: 'column',
  overflow: 'hidden',
} as const);

const row = {
  height: '52px',
  paddingLeft: '16px',
  paddingRight: '16px',
  display: 'flex',
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
} as const;

const labelStyle = () => ({ fontSize: '17px', color: colors.text } as const);

function Separator() {
  return <view style={{ height: '1px', marginLeft: '16px', backgroundColor: colors.separator }} />;
}

export function SettingsScreen({ settings, noteCount, onChange, onReset }: {
  settings: Settings;
  noteCount: number;
  onChange: (s: Settings) => void;
  onReset: () => void;
}) {
  const sortLabel = settings.sort === 'updated' ? 'Updated' : 'Title';
  const appearanceLabel = APPEARANCE_LABEL[settings.appearance];
  return (
    <view style={{ flexGrow: 1, flexShrink: 1, flexBasis: '0px', display: 'flex', flexDirection: 'column' }}>
      <ScreenHeader title='Settings' />
      <view style={{ ...groupStyle(), marginTop: '12px' }}>
        <view
          {...a11y('sort-row', `Sort by, ${sortLabel}`, { 'accessibility-value': sortLabel, 'accessibility-traits': 'button' })}
          style={row}
          bindtap={() => onChange({ ...settings, sort: settings.sort === 'updated' ? 'title' : 'updated' })}
        >
          <text style={labelStyle()}>Sort by</text>
          <text style={{ fontSize: '17px', color: colors.accent }}>{sortLabel}</text>
        </view>
        <Separator />
        <view style={{ ...row, height: '51px' }}>
          <text style={labelStyle()}>Show snippets</text>
          <Switch
            id='snippets-switch'
            label='Show snippets'
            value={settings.showSnippets}
            onChange={(v) => onChange({ ...settings, showSnippets: v })}
          />
        </view>
        <Separator />
        <view
          {...a11y('appearance-row', `Appearance, ${appearanceLabel}`, {
            'accessibility-value': appearanceLabel,
            'accessibility-traits': 'button',
          })}
          style={{ ...row, height: '51px' }}
          bindtap={() => onChange({ ...settings, appearance: NEXT_APPEARANCE[settings.appearance] })}
        >
          <text style={labelStyle()}>Appearance</text>
          <text style={{ fontSize: '17px', color: colors.accent }}>{appearanceLabel}</text>
        </view>
        <Separator />
        <view style={{ ...row, height: '51px' }}>
          <text style={labelStyle()}>Notes</text>
          <text {...a11y('notes-count', String(noteCount))} style={{ fontSize: '17px', color: colors.textTertiary }}>
            {String(noteCount)}
          </text>
        </view>
      </view>
      <view style={{ ...groupStyle(), marginTop: '24px' }}>
        <view
          {...a11y('reset-button', 'Reset sample notes', { 'accessibility-traits': 'button' })}
          style={{ ...row, justifyContent: 'center' }}
          bindtap={onReset}
        >
          <text style={{ fontSize: '17px', color: colors.danger }}>Reset sample notes</text>
        </view>
      </view>
      <text style={{ marginTop: '16px', fontSize: '13px', color: colors.textTertiary, textAlign: 'center' }}>
        {'Markdown Notes · v1.0'}
      </text>
    </view>
  );
}

// angular-native/src/app/screens/settings-screen.ts
import { Component, computed, inject } from '@angular/core';
import { Pressable, ScrollView, Text, View } from '@ng-native/components';
import { NotesStore } from '../data/notes-store.ts';
import { ScreenHeader } from '../ui/screen-header.ts';
import { ToggleSwitch } from '../ui/toggle-switch.ts';

@Component({
  selector: 'app-settings-screen',
  imports: [Pressable, ScreenHeader, ScrollView, Text, ToggleSwitch, View],
  host: { style: 'flex: 1' },
  template: `
    <app-screen-header title="Settings" />
    <scroll-view class="scroll" [contentContainerStyle]="{ paddingTop: 12, paddingHorizontal: 16, paddingBottom: 16 }">
      <view class="group">
        <pressable testID="sort-row" accessibilityRole="button" class="row" (press)="store.toggleSortOrder()">
          <text class="label">Sort by</text>
          <text class="value">{{ store.sortOrder() === 'title' ? 'Title' : 'Updated' }}</text>
        </pressable>
        <view class="separator"></view>
        <view class="row">
          <text class="label">Show snippets</text>
          <app-toggle-switch
            testID="snippets-switch"
            label="Show snippets"
            [checked]="store.showSnippets()"
            (toggle)="store.toggleSnippets()"
          />
        </view>
        <view class="separator"></view>
        <pressable testID="appearance-row" accessibilityRole="button" class="row" (press)="store.cycleAppearance()">
          <text class="label">Appearance</text>
          <text class="value">{{ appearanceLabel() }}</text>
        </pressable>
        <view class="separator"></view>
        <view class="row">
          <text class="label">Notes</text>
          <text testID="notes-count" class="count">{{ store.count() }}</text>
        </view>
      </view>

      <view class="group second">
        <pressable testID="reset-button" accessibilityRole="button" class="row center" (press)="store.resetSamples()">
          <text class="danger">Reset sample notes</text>
        </pressable>
      </view>

      <text class="footer">Markdown Notes · v1.0</text>
    </scroll-view>
  `,
  styles: `
    .scroll {
      flex: 1;
    }
    .group {
      background-color: var(--surface);
      border-radius: 14px;
      overflow: hidden;
    }
    .second {
      margin-top: 24px;
    }
    .row {
      height: 52px;
      padding-left: 16px;
      padding-right: 16px;
      flex-direction: row;
      align-items: center;
      justify-content: space-between;
    }
    .center {
      justify-content: center;
    }
    .separator {
      height: 1px;
      margin-left: 16px;
      background-color: var(--separator);
    }
    .label {
      font-size: 17px;
      color: var(--text);
    }
    .value {
      font-size: 17px;
      color: var(--accent);
    }
    .count {
      font-size: 17px;
      color: var(--text-tertiary);
    }
    .danger {
      font-size: 17px;
      color: var(--danger);
    }
    .footer {
      margin-top: 16px;
      font-size: 13px;
      color: var(--text-tertiary);
      text-align: center;
    }
  `,
})
export class SettingsScreen {
  protected readonly store = inject(NotesStore);
  protected readonly appearanceLabel = computed(() => {
    const a = this.store.appearance();
    return a === 'light' ? 'Light' : a === 'dark' ? 'Dark' : 'System';
  });
}
