// react-native/src/screens/SettingsScreen.tsx
import React from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { useNotes } from '../data/NotesStore';
import type { Appearance } from '../data/types';
import { makeStyles } from '../theme';
import { IdText } from '../ui/IdText';
import { ScreenHeader } from '../ui/ScreenHeader';
import { Toggle } from '../ui/Toggle';

const APPEARANCE_LABEL: Record<Appearance, string> = { system: 'System', light: 'Light', dark: 'Dark' };
const NEXT_APPEARANCE: Record<Appearance, Appearance> = { system: 'light', light: 'dark', dark: 'system' };

export function SettingsScreen() {
  const styles = useStyles();
  const { notes, settings, updateSettings, resetSamples } = useNotes();
  const appearanceLabel = APPEARANCE_LABEL[settings.appearance];
  const sortLabel = settings.sortBy === 'updated' ? 'Updated' : 'Title';
  return (
    <View style={{ flex: 1 }}>
      <ScreenHeader title="Settings" />
      <ScrollView contentContainerStyle={styles.content}>
        <View style={styles.group}>
          <Pressable
            testID="sort-row"
            accessibilityRole="button"
            accessibilityLabel={`Sort by, ${sortLabel}`}
            accessibilityValue={{ text: sortLabel }}
            style={styles.row}
            onPress={() => updateSettings({ sortBy: settings.sortBy === 'updated' ? 'title' : 'updated' })}
          >
            <Text style={styles.label}>Sort by</Text>
            <Text style={styles.value}>{sortLabel}</Text>
          </Pressable>
          <View style={styles.separator} />
          <View style={styles.row}>
            <Text style={styles.label}>Show snippets</Text>
            <Toggle
              testID="snippets-switch"
              label="Show snippets"
              value={settings.showSnippets}
              onChange={(v) => updateSettings({ showSnippets: v })}
            />
          </View>
          <View style={styles.separator} />
          <Pressable
            testID="appearance-row"
            accessibilityRole="button"
            accessibilityLabel={`Appearance, ${appearanceLabel}`}
            accessibilityValue={{ text: appearanceLabel }}
            style={styles.row}
            onPress={() => updateSettings({ appearance: NEXT_APPEARANCE[settings.appearance] })}
          >
            <Text style={styles.label}>Appearance</Text>
            <Text style={styles.value}>{appearanceLabel}</Text>
          </Pressable>
          <View style={styles.separator} />
          <View style={styles.row}>
            <Text style={styles.label}>Notes</Text>
            <IdText testID="notes-count" style={styles.count}>
              {notes.length}
            </IdText>
          </View>
        </View>
        <View style={[styles.group, styles.group2]}>
          <Pressable
            testID="reset-button"
            accessibilityRole="button"
            accessibilityLabel="Reset sample notes"
            style={[styles.row, styles.centerRow]}
            onPress={resetSamples}
          >
            <Text style={styles.danger}>Reset sample notes</Text>
          </Pressable>
        </View>
        <Text style={styles.footer}>Markdown Notes · v1.0</Text>
      </ScrollView>
    </View>
  );
}

const useStyles = makeStyles((colors) => ({
  content: { paddingTop: 12, paddingBottom: 16 },
  group: { marginHorizontal: 16, backgroundColor: colors.surface, borderRadius: 14, overflow: 'hidden' },
  group2: { marginTop: 24 },
  row: {
    height: 52,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  centerRow: { justifyContent: 'center' },
  separator: { height: 1, marginLeft: 16, backgroundColor: colors.separator },
  label: { fontSize: 17, color: colors.text },
  value: { fontSize: 17, color: colors.accent },
  count: { fontSize: 17, color: colors.textTertiary },
  danger: { fontSize: 17, color: colors.danger },
  footer: { marginTop: 16, textAlign: 'center', fontSize: 13, color: colors.textTertiary },
}));

// angular-native/src/app/screens/settings-screen.ts
import { Component, computed, inject } from '@angular/core';
import { Pressable, ScrollView, Text, View } from '@ng-native/components';
import { NotesStore } from '../data/notes-store.ts';
import { ScreenHeader } from '../ui/screen-header.ts';
import { ToggleSwitch } from '../ui/toggle-switch.ts';

@Component({
  selector: 'app-settings-screen',
  imports: [Pressable, ScreenHeader, ScrollView, Text, ToggleSwitch, View],
  host: { style: 'flex: 1' },
  template: `
    <app-screen-header title="Settings" />
    <scroll-view class="scroll" [contentContainerStyle]="{ paddingTop: 12, paddingHorizontal: 16, paddingBottom: 16 }">
      <view class="group">
        <pressable testID="sort-row" accessibilityRole="button" class="row" (press)="store.toggleSortOrder()">
          <text class="label">Sort by</text>
          <text class="value">{{ store.sortOrder() === 'title' ? 'Title' : 'Updated' }}</text>
        </pressable>
        <view class="separator"></view>
        <view class="row">
          <text class="label">Show snippets</text>
          <app-toggle-switch
            testID="snippets-switch"
            label="Show snippets"
            [checked]="store.showSnippets()"
            (toggle)="store.toggleSnippets()"
          />
        </view>
        <view class="separator"></view>
        <pressable testID="appearance-row" accessibilityRole="button" class="row" (press)="store.cycleAppearance()">
          <text class="label">Appearance</text>
          <text class="value">{{ appearanceLabel() }}</text>
        </pressable>
        <view class="separator"></view>
        <view class="row">
          <text class="label">Notes</text>
          <text testID="notes-count" class="count">{{ store.count() }}</text>
        </view>
      </view>

      <view class="group second">
        <pressable testID="reset-button" accessibilityRole="button" class="row center" (press)="store.resetSamples()">
          <text class="danger">Reset sample notes</text>
        </pressable>
      </view>

      <text class="footer">Markdown Notes · v1.0</text>
    </scroll-view>
  `,
  styles: `
    .scroll {
      flex: 1;
    }
    .group {
      background-color: var(--surface);
      border-radius: 14px;
      overflow: hidden;
    }
    .second {
      margin-top: 24px;
    }
    .row {
      height: 52px;
      padding-left: 16px;
      padding-right: 16px;
      flex-direction: row;
      align-items: center;
      justify-content: space-between;
    }
    .center {
      justify-content: center;
    }
    .separator {
      height: 1px;
      margin-left: 16px;
      background-color: var(--separator);
    }
    .label {
      font-size: 17px;
      color: var(--text);
    }
    .value {
      font-size: 17px;
      color: var(--accent);
    }
    .count {
      font-size: 17px;
      color: var(--text-tertiary);
    }
    .danger {
      font-size: 17px;
      color: var(--danger);
    }
    .footer {
      margin-top: 16px;
      font-size: 13px;
      color: var(--text-tertiary);
      text-align: center;
    }
  `,
})
export class SettingsScreen {
  protected readonly store = inject(NotesStore);
  protected readonly appearanceLabel = computed(() => {
    const a = this.store.appearance();
    return a === 'light' ? 'Light' : a === 'dark' ? 'Dark' : 'System';
  });
}
