// angular-native/src/app/ui/note-card.ts
import { Component, computed, input, output } from '@angular/core';
import { Pressable, Text, View } from '@ng-native/components';
import { type Note, formatDate, noteSnippet, noteTags, noteTitle, taskProgress } from '../data/note.ts';

@Component({
  selector: 'app-note-card',
  imports: [Pressable, Text, View],
  template: `
    <pressable
      testID="note-card"
      accessibilityRole="button"
      class="card"
      #p="pressable"
      [style.opacity]="p.pressed() ? 0.7 : 1"
      (press)="open.emit(note().id)"
    >
      <text class="title" [numberOfLines]="1">{{ title() }}</text>
      @if (showSnippet() && snippet()) {
        <text class="snippet" [numberOfLines]="2">{{ snippet() }}</text>
      }
      @if (tags().length > 0) {
        <view class="chips">
          @for (tag of tags(); track tag) {
            <view class="chip">
              <text class="chip-text" [numberOfLines]="1">#{{ tag }}</text>
            </view>
          }
        </view>
      }
      <view class="footer">
        <view class="meta">
          <text class="date">{{ date() }}</text>
          @if (progress().total > 0) {
            <text class="progress">{{ progress().done }}/{{ progress().total }} done</text>
          }
        </view>
        @if (note().starred) {
          <text class="star">★</text>
        }
      </view>
    </pressable>
  `,
  styles: `
    .card {
      background-color: var(--surface);
      border-radius: 14px;
      padding: 16px;
    }
    .title {
      font-size: 17px;
      line-height: 22px;
      font-weight: 600;
      color: var(--text);
    }
    .snippet {
      margin-top: 4px;
      font-size: 15px;
      line-height: 20px;
      color: var(--text-secondary);
    }
    .chips {
      margin-top: 8px;
      flex-direction: row;
      gap: 6px;
      overflow: hidden;
    }
    .chip {
      height: 22px;
      padding-left: 8px;
      padding-right: 8px;
      border-radius: 11px;
      background-color: var(--accent-soft);
      justify-content: center;
      flex-shrink: 0;
    }
    .chip-text {
      font-size: 12px;
      font-weight: 500;
      color: var(--accent);
    }
    .footer {
      margin-top: 8px;
      flex-direction: row;
      align-items: center;
      justify-content: space-between;
      height: 18px;
    }
    .date {
      font-size: 13px;
      line-height: 18px;
      color: var(--text-tertiary);
    }
    .meta {
      flex-direction: row;
      align-items: center;
      gap: 12px;
    }
    .progress {
      font-size: 13px;
      line-height: 18px;
      color: var(--text-secondary);
    }
    .star {
      font-size: 16px;
      line-height: 18px;
      color: var(--star);
    }
  `,
})
export class NoteCard {
  readonly note = input.required<Note>();
  readonly showSnippet = input(true);
  readonly open = output<string>();

  protected readonly title = computed(() => noteTitle(this.note().body));
  protected readonly snippet = computed(() => noteSnippet(this.note().body));
  protected readonly tags = computed(() => noteTags(this.note().body));
  protected readonly progress = computed(() => taskProgress(this.note().body));
  protected readonly date = computed(() => formatDate(this.note().updatedAt));
}

// react-native/src/ui/NoteCard.tsx
import React from 'react';
import { Pressable, Text, View } from 'react-native';
import { dateLabel, noteSnippet, noteTitle } from '../data/noteText';
import { extractTags } from '../data/tags';
import { taskProgress } from '../data/tasks';
import type { Note } from '../data/types';
import { makeStyles } from '../theme';

export const NoteCard = React.memo(function NoteCard({
  note,
  showSnippet,
  onPress,
}: {
  note: Note;
  showSnippet: boolean;
  onPress: (id: string) => void;
}) {
  const styles = useStyles();
  const title = noteTitle(note.body);
  const snippet = showSnippet ? noteSnippet(note.body) : '';
  const tags = extractTags(note.body);
  const progress = taskProgress(note.body);
  return (
    <Pressable
      testID="note-card"
      accessibilityRole="button"
      accessibilityLabel={title}
      onPress={() => onPress(note.id)}
      style={styles.card}
    >
      <Text style={styles.title} numberOfLines={1}>
        {title}
      </Text>
      {snippet.length > 0 && (
        <Text style={styles.snippet} numberOfLines={2}>
          {snippet}
        </Text>
      )}
      {tags.length > 0 && (
        <View style={styles.tags}>
          {tags.map((t) => (
            <View key={t} style={styles.tag}>
              <Text style={styles.tagText} numberOfLines={1}>
                #{t}
              </Text>
            </View>
          ))}
        </View>
      )}
      <View style={styles.footer}>
        <View style={styles.footerLeft}>
          <Text style={styles.date}>{dateLabel(note.updatedAt)}</Text>
          {progress.total > 0 && (
            <Text style={styles.progress}>
              {progress.done}/{progress.total} done
            </Text>
          )}
        </View>
        {note.starred && <Text style={styles.star}>★</Text>}
      </View>
    </Pressable>
  );
});

const useStyles = makeStyles((colors) => ({
  card: { backgroundColor: colors.surface, borderRadius: 14, padding: 16 },
  title: { fontSize: 17, lineHeight: 22, fontWeight: '600', color: colors.text },
  snippet: { marginTop: 4, fontSize: 15, lineHeight: 20, color: colors.textSecondary },
  tags: { marginTop: 8, flexDirection: 'row', flexWrap: 'nowrap', overflow: 'hidden', gap: 6 },
  tag: {
    height: 22,
    paddingHorizontal: 8,
    borderRadius: 11,
    backgroundColor: colors.accentSoft,
    justifyContent: 'center',
    flexShrink: 0,
  },
  tagText: { fontSize: 12, fontWeight: '500', color: colors.accent },
  footer: { marginTop: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 18 },
  footerLeft: { flexDirection: 'row', alignItems: 'center' },
  progress: { marginLeft: 12, fontSize: 13, lineHeight: 18, color: colors.textSecondary },
  date: { fontSize: 13, lineHeight: 18, color: colors.textTertiary },
  star: { fontSize: 16, lineHeight: 18, color: colors.star },
}));
