// angular-native/src/app/ui/tab-bar.ts
import { Component, inject, input, output } from '@angular/core';
import { Pressable, Text, View } from '@ng-native/components';
import { SafeArea } from '@ng-native/device';

export type Tab = 'notes' | 'starred' | 'settings';

const TABS: readonly { id: Tab; label: string }[] = [
  { id: 'notes', label: 'Notes' },
  { id: 'starred', label: 'Starred' },
  { id: 'settings', label: 'Settings' },
];

/** Custom-drawn bottom tab bar: three text-only, equal-width columns. */
@Component({
  selector: 'app-tab-bar',
  imports: [Pressable, Text, View],
  template: `
    <view class="bar" [style.paddingBottom]="safeArea.insets().bottom">
      <view class="line"></view>
      <view class="row">
        @for (tab of tabs; track tab.id) {
          <pressable
            class="tab"
            [testID]="'tab-' + tab.id"
            accessibilityRole="button"
            [accessibilityState]="{ selected: active() === tab.id }"
            [accessibilityLabel]="tab.label"
            (press)="select.emit(tab.id)"
          >
            <text class="label" [class.active]="active() === tab.id">{{ tab.label }}</text>
          </pressable>
        }
      </view>
    </view>
  `,
  styles: `
    .bar {
      background-color: var(--surface);
    }
    .line {
      height: 1px;
      background-color: var(--separator);
    }
    .row {
      height: 56px;
      flex-direction: row;
    }
    .tab {
      flex: 1;
      align-items: center;
      justify-content: center;
    }
    .label {
      font-size: 15px;
      font-weight: 500;
      color: var(--text-tertiary);
    }
    .active {
      font-weight: 600;
      color: var(--accent);
    }
  `,
})
export class TabBar {
  protected readonly safeArea = inject(SafeArea);
  protected readonly tabs = TABS;
  readonly active = input.required<Tab>();
  readonly select = output<Tab>();
}

// react-native/src/ui/TabBar.tsx
import React from 'react';
import { Pressable, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { makeStyles } from '../theme';

export type TabKey = 'notes' | 'starred' | 'settings';

const TABS: { key: TabKey; label: string }[] = [
  { key: 'notes', label: 'Notes' },
  { key: 'starred', label: 'Starred' },
  { key: 'settings', label: 'Settings' },
];

export function TabBar({ active, onChange }: { active: TabKey; onChange: (t: TabKey) => void }) {
  const styles = useStyles();
  const insets = useSafeAreaInsets();
  return (
    <View style={[styles.bar, { paddingBottom: insets.bottom }]}>
      {TABS.map((t) => {
        const selected = t.key === active;
        return (
          <Pressable
            key={t.key}
            testID={`tab-${t.key}`}
            accessibilityRole="button"
            accessibilityState={{ selected }}
            accessibilityLabel={t.label}
            style={styles.tab}
            onPress={() => onChange(t.key)}
          >
            <Text style={[styles.label, selected ? styles.active : styles.inactive]}>{t.label}</Text>
          </Pressable>
        );
      })}
    </View>
  );
}

const useStyles = makeStyles((colors) => ({
  bar: {
    flexDirection: 'row',
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.separator,
  },
  tab: { flex: 1, height: 55, alignItems: 'center', justifyContent: 'center' },
  label: { fontSize: 15 },
  active: { color: colors.accent, fontWeight: '600' },
  inactive: { color: colors.textTertiary, fontWeight: '500' },
}));
